--user:marko123 psw:asdasd

CREATE TABLE postType (
    posttype_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    posttype_name VARCHAR(32)
);

CREATE TABLE utenti (
    utente_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(256) UNIQUE,
    nome VARCHAR(256),
    cognome VARCHAR(256),
    password VARCHAR(256) NOT NULL,
    urlFotoProfilo VARCHAR(256),
    fraseDiPresentazione VARCHAR(256),
    dataNascita VARCHAR(256)
);

CREATE TABLE posts (
    post_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content VARCHAR(1024),
    type INTEGER,
    FOREIGN KEY (type) REFERENCES postType(posttype_id),
    author INTEGER,
    FOREIGN KEY (author) REFERENCES utenti(utente_id)
);

CREATE TABLE gruppi( 
    group_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomeGruppo VARCHAR(1024),
    listaUtentiGruppo INTEGER,
    FOREIGN KEY (listaUtentiGruppo) REFERENCES utenti(utente_id)
);

ALTER TABLE gruppi ADD listaUtentiGruppo INTEGER; 
ALTER TABLE gruppi ADD FOREIGN KEY(listaUtentiGruppo) REFERENCES utenti(utente_id);



CREATE TABLE amicizie (
   follower INTEGER,
   FOREIGN KEY (follower) REFERENCES utenti(utente_id),
   followed INTEGER,
   FOREIGN KEY (followed) REFERENCES utenti(utente_id),
   PRIMARY KEY (follower, followed)
);

ALTER TABLE posts ADD text VARCHAR(1024);


INSERT INTO utenti (utente_id, username, nome, cognome, password, urlfotoprofilo, frasedipresentazione, datanascita)
VALUES (default,
        'igna123',
        'Ignazio',
        'Meh',
        '123',
        'M2/img/user1.jpeg',
        'non so cosa scrivere',
        '11/11/1980');

INSERT INTO utenti (utente_id, username, nome, cognome, password, urlfotoprofilo, frasedipresentazione, datanascita)
VALUES (default,
        'giampy123',
        'Giampaolo',
        'Pazzini',
        'moviolivo',
        'M2/img/user2.jpeg',
        'attualmente giocatore Hellas Verona',
        '02/08/1984');

INSERT INTO utenti (utente_id, username, nome, cognome, password, urlfotoprofilo, frasedipresentazione, datanascita)
VALUES (default,
        'marko123',
        'Marco',
        'Brundu',
        'asdasd',
        'M2/img/user3.jpeg',
        'mai una gioia',
        '16/10/1993');
INSERT INTO utenti (utente_id, username, nome, cognome, password, urlfotoprofilo, frasedipresentazione, datanascita)
VALUES (default,
        'missing123',
        '',
        '',
        '0123',
        '',
        'eeeesd',
        '01/01/1999');

INSERT INTO posttype (posttype_id, posttype_name)
VALUES (default, 'TEXT');

INSERT INTO posttype (posttype_id, posttype_name)
VALUES (default, 'IMAGE');

INSERT INTO posttype (posttype_id, posttype_name)
VALUES (default, 'URL');


INSERT INTO posts (post_id, content, type, author, text)
VALUES (default,
        '',
        1,
        1,
        'Ognuna di quelle vite e quella giusta. Ogni percorso e il giusto percorso. Ogni cosa avrebbe potuto essere un altra e avrebbe avuto lo stesso profondo significato.(Nemo Nobody)');
INSERT INTO posts (post_id, content, type, author, text)
VALUES (default,
        'img/gol.jpeg',
        2,
        2,
        'CHE GOOOL DI KAKA');

INSERT INTO posts (post_id, content, type, author, text)
VALUES (default,
        'https://tinyurl.com/k34etds',
        3,
        3,
        'eh si � proprio vero');


INSERT INTO amicizie (follower, followed)
VALUES (1, 2),
       (1, 3),
       (2, 4),
       (3, 1),
       (3, 2);

INSERT INTO gruppi (group_id, nomegruppo, listautentigruppo)
VALUES (default,
        'MilanGroup',
        (1);